config/routes.rb
Rails.application.routes.draw do

  get 'estadisticas', to: 'estadisticas#index'
  get "estadisticas/programaciones/detalles/:year/:month", to: "estadisticas#show_programaciones", as: :programaciones_show
  get "estadisticas/clientes/detalles/:year", to: "estadisticas#show_cliente", as: :clientes_show
  get "estadisticas/clientes/mes/:year_month", to: "estadisticas#show_month_cliente", as: :clientes_month_show
  namespace :estadisticas do
    get :clientes
    get :programaciones
  end

  # Rutas para las programaciones
  match 'programaciones/remove_from_programing/:month', to: 'programaciones#remove_from_programing', as: :remove_from_programing, via: [:post, :patch] # Para editar un atributo concreto; es patch
  get 'programaciones/program_table/:month', to: 'programaciones#program_table', as: :program_table
  get 'programaciones/modal_open/:month', to: 'programaciones#modal_open', as: :modal_open  # Leer recurso; es get
  get 'programaciones/options_export/:month', to: 'programaciones#options_export', as: :programacion_options_export
  resources :programaciones, only:[:index] do
    # Más información sobre collection http://guides.rubyonrails.org/routing.html#adding-collection-routes
    get :export_pdf, on: :collection
    get :export_excel, on: :member
    get :get_row, on: :collection
    patch :generate, on: :member # Editar una parte concreta, es patch
    patch :add_lotes_to_programing, as: :add_lotes, on: :collection # Para editar un atributo concreto; es patch
    patch :update_row_order, on: :collection
  end

  # Rutas de los usuarios
  devise_for :users
  resources :users, except: [:create] do
    post 'new' => 'users#create', as: :create, on: :collection
    patch :lock, on: :member
    patch :unlock, on: :member
  end

  # Rutas de los lotes
  resources :lotes do
    get :autocomplete_color_color, :on => :collection
    get :options_export, :on => :collection
    get :export_excel, :on => :collection
    get :view_details           # es método get, y parte de los lotes
    patch :cambio_estado        # Este es patch y debe pertenecer a los lotes
    patch :total_price, on: :member # esta es un patch y pertenece a los lotes
    patch :update_ingresara_a_planta, on: :member
    patch :update_programacion, on: :member
    resources :control_lotes do 
      patch :update_cantidad, on: :member
    end
    post :validate_op
  end

  resources :control_lotes do
    resources :seguimientos
  end

  # Otras rutas
  resources :sub_estados, :referencias, :tipos_prendas, :tallas, :roles, :clientes
  resources :calendario, except: :show
  resources :estados do
    patch :lock, on: :member
    patch :unlock, on: :member
  end
  # get "clientes/send_email" => 'clientes#send_email', :as => :send_email # debe pertenecer a los clientes y tener el id del cliente a quien se envía el correo

  get '/sobre-confecab', to: 'static_pages#about_confecab', as: :about_confecab
  get '/sobre-disenos-y-camisas', to: 'static_pages#about_dyc', as: :about_dyc
  # Inicio de la aplicación
  root :to => 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # http://guides.rubyonrails.org/routing.html#non-resourceful-routes
end

app/controllers/lotes_controller.rb
=begin
  CONTROLADOR DE LOTES
Todas las acciones a la vista de acuerdo con el paradigma MVC
=end
class LotesController < ApplicationController
  # Validación de autorización
  load_and_authorize_resource :except => [:view_details]
  include LotesHelper
  include LotesDatatablesHelper
  # Acciones primarias
  before_action :rol_user, only: [:create, :update, :edit, :new]
  before_action :set_color, only: [:create, :update]
  before_action :set_tipo_prenda, only: [:new, :edit]
  before_action :set_lote, only: [:edit, :update, :update_ingresara_a_planta, :update_programacion, :destroy]
  before_action :set_talla, only: [:view_details, :new, :edit, :create, :update]
  before_action :time, only: [:cambio_estado]

  # Autocompletado
  autocomplete :color, :color

  # GET /lotes
  # GET /lotes.json
  def index
    @estados = Estado.active.order(:secuencia)
    respond_to do |format|
      format.html
      format.js
      format.json { render json: data_tables(params) }
    end
  end

  def view_details
    lote_id = params.permit(:lote_id)
    @lote = ControlLote.where(lote_id: lote_id[:lote_id]).max
    respond_to do |format|
      format.js
    end
  end

  # GET /lotes/new
  def new
    @lote = Lote.new
    @colores_lotes = @lote.colores_lotes.build
    @cantidades = @colores_lotes.cantidades.build
    @control_lote = @lote.control_lotes.build
  end

  # GET /lotes/1/edit
  def edit
    # Si cuando el lote fue guardado se guardó sin tener detalles de las
    # cantidades se construye un grupo nuevo de campos para el formulario
    if @lote.colores_lotes.empty?
      @colores_lotes = @lote.colores_lotes.build
      (0..8).each { |n| @cantidades = @colores_lotes.cantidades.build }
    else
      # En caso de tenerlos, se adapta la situación para que imprima lo que ya existe en 
      # en el formulario
      @totales = Array.new
      @colores = Array.new
      @totales_tallas = Array.new
      @lote.colores_lotes.each do |cl|
        @totales.push cl.total.total
        @colores.push cl.color.color
        cl.cantidades.each do |c|
          @totales_tallas.push c.total.total
        end
      end
    end
  end


  # POST /lotes
  # POST /lotes.json
  def create
    # Definir si la op existe. Retorna true si puede ser creada
    @lote = Lote.new(lote_params)
    respond_to do |format|
      if @color_blank
        if @lote.save
          @control = @lote.control_lotes.last
          @control.update(resp_ingreso_id: current_user, fecha_ingreso: Time.new)
          @control.seguimientos.new(cantidad: @lote.cantidad).save
          format.html { redirect_to lotes_path }
        else
          invalid = true
        end
      else
        invalid = true
        @lote.errors.add :colores_lotes
      end
      if invalid
        set_tipo_prenda
        if @remove
          @colores_lotes = @lote.colores_lotes.build
          (0..8).each { |n| @cantidades = @colores_lotes.cantidades.build }
        end
        format.html { render :new }
        format.json { render json: @lote.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /lotes/1
  # PATCH/PUT /lotes/1.json
  def update
    respond_to do |format|
      if @lote.update(lote_params_update) && @color_blank
        format.html { redirect_to "/#{params[:lote][:plc]}" }
        flash[:success] = "Lote actualizado correctamente"
      else
        set_tipo_prenda
        if !@color_blank
          @lote.errors.add :colores_lotes
        end
        format.html { render :edit }
        format.json { render json: @lote.errors, status: :unprocessable_entity }
      end
    end
  end

  # Pasar entre los distintos estados del lote y registrar las fechas de salida
  # de un estado, la de entrada al siguiente y un responsable por acción
  def cambio_estado
    this = Lote
    @next_estado = Estado.find params[:btn] # Lote siguiente del actual
    @estado = @next_estado.id # Este es el estado que sigue del actual
    @men = @next_estado.estado
    has_programing = this.has_programing(params[:lote_id], @estado)

    if has_programing
      # Actualización de fecha para el último estado
      @lote = this.find(params[:lote_id])
      # Asignación de parámetros para el nuevo control a registrar. Responsable
      # por el movimiento
      @control = ControlLote.new(:lote_id => params[:lote_id], :estado_id => @estado,
                                      :fecha_ingreso => @time, :resp_ingreso_id => current_user)
      respond_to do |format|
        # Nuevo estado en el historial de los lotes
        if @control.save
          Seguimiento.seguimientos_status_change(@lote.cantidad, @control, current_user, action_name)
          reqfor = request.format # formato de la solicitud
          if reqfor == "application/json" || reqfor == "text/javascript"
            format.json { render json: json_cambio_estado, status: :ok }
            format.js { render 'control_lotes/cambio_estado' }
          else
            format.html { redirect_to :back }
            flash[:info] = "Lote #{men=="completado" ? men : "cambiado a #{men}"}."
          end

        else
          format.html { redirect_to lotes_path }
          flash[:danger] = "Ocurrio un error, intenta de nuevo"
        end
      end
    else
      respond_to do |format|
        if request.format == "text/javascript"
          format.html { render partial: 'dropdown_options', locals: {lote_id: params[:lote_id], estado_id: @estado - 1},
                               status: :not_modified }
        else
          format.html { redirect_to :back }
        end

      end
    end
  end

  def update_ingresara_a_planta
    respond_to do |format|
      if @lote.update(params.require(:lote).permit(:ingresara_a_planta))
        format.json { render json: @lote, status: :ok }
      else
        head :bad_request # Código 400 en los estados HTTP
      end
    end
  end

  def update_programacion
    par = params.require(:lote).permit(:year, :month, :day)
    par[:month] = "0#{par[:month]}" if par[:month].to_i < 10
    programacion = Programacion.get_per_month("#{par[:year]}#{par[:month]}", session[:selected_company])
    respond_to do |format|
      if @lote.update(:programacion_id => programacion.first.id, :ingresara_a_planta => "#{par[:year]}-#{par[:month]}-#{par[:day]}")
        format.json { render json: @lote, status: :ok }
      else
        head :bad_request # Código 400 en los estados HTTP
      end
    end
  end

  # DELETE /lotes/1
  # DELETE /lotes/1.json
  def destroy
    @lote.destroy
    render json: {message: "Lote eliminado."}, status: :ok
  end

  # PATCH /lotes/:lote_id/total_price
  # Actualiza los precios (total y unitario) del lote
  def total_price
    lote_price = params.require(:lote).permit(:amount, :unit_price)
    lote_price[:unit_price] = Lote.functional_format lote_price[:unit_price]
    price_total = Lote.multiplication(lote_price.values)
    format_price_u = Money.from_amount(lote_price[:unit_price].to_i, "COP").format(:no_cents => true)
    format_price_t = Money.from_amount(price_total.to_i, "COP").format(:no_cents => true)
    Lote.update(params[:id].to_i, :precio_u => lote_price[:unit_price], :precio_t => price_total, :respon_edicion_id => current_user)
    @prices = {:total => format_price_t, :unit => format_price_u}
    respond_to do |format|
      format.json { render json: @prices }
    end
  end

  def options_export
    company = session[:selected_company]
    @clientes = Cliente.all.where(:empresa => company)
  end

  def export_excel
    # Hash con las claves y valores que fueron seleccionados
    @keys = Lote.set_keys_query permit_export
    company = session[:selected_company] ? "CAB" : "D&C"
    permit = Hash.new
    permit[:from] = params[:export][:from]
    permit[:to] = params[:export][:to]
    permit[:clientes] = params[:export][:clientes]

    @lotes = Lote.query_filtered permit, company
    company = session[:selected_company] ? "Confecab" : "Diseños y camisas"
    respond_to do |format|
      format.xlsx { render xlsx: "export_excel", filename: "Lotes de #{company}" }
    end
  end

  # POST /lotes/:lote_id/
  def validate_op
    op_param = params.permit(:op, :lote_id)
    company = session[:selected_company] ? "CAB" : "D&C"
    lote_id = op_param[:lote_id] == "undefinded" ? nil : op_param[:lote_id]
    val_op = Lote.validate_op(op_param[:op], company, lote_id)
    respond_to do |format|
      format.json { render json: val_op }
    end
  end

  private
  def set_lote
    @lote = Lote.find(params[:id])
  end

  def set_tipo_prenda
    @tipos_prendas = TipoPrenda.all
    @clientes = Cliente.where(:empresa => session[:selected_company])
    @sub_estados = SubEstado.all
  end

  def set_lote_u
    @lote = ControlLote.where(lote_id: params[:lote_id]).max
  end

  def set_talla
    @tallas = Talla.all
  end

  def set_referencia
    id = Referencia.find_or_create_by(:referencia => params[:lote][:referencia])
    id.id
  end

  # Validación de los datos del color.
  # Define que para todas las tallas exista por lo menos una cantidad mayor a 0
  # Determina que el campo para el color no esté vacío
  # Asigna las variables correspondientes para reanudar el formulario en caso de fallar esta validación.
  # Cómo buena práctica debería estar en el modelo de lote o de color. Puede ser pasado teniendo presentes todas las
  # implicaciones en ello
  def set_color
    # Totales: Array para los totales por tallas
    totales = Array.new
    color_id = nil
    total_cantidades_id = nil
    total_colores_id = nil
    bool = true
    recorrer_una = true

    # Zona de acción en caso de que las validaciones correspondientes
    # sean inválidas
    # remove: Indica si debe armarse de nuevo el formulario de detalles de cantidades
    # colores: Toma los colores de los parámetros antes de que sean analizados para
    # que no se pierdan para la vista
    # color_blank: Retorna true si hay un color
    # totales: totales relativos por color
    # totales_tallas: totales por talla

app/helpers/lotes_helper.rb
module LotesHelper

  def link_to_add_fields(name, clase = nil, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |colores_lotes_for_form|
      render( partial: association.to_s.singularize + "_fields", locals:{
        f: colores_lotes_for_form, b: true, col:"", total:""})
    end
    link_to name, '', class: "#{clase}", 
    data: { id: id, fields: fields.gsub("\n", "")}, :title => "Más cantidades"
  end

  def date_form_value(lote)
    if !@lote.programacion.nil?
      I18n::localize(@lote.programacion.mes, :format => "%B %Y")
    end
  end

  def def_names(keys)
    names = Array.new
    modify = { 
      no_remision: "Número de remisión",
      no_factura: "Número de factura",
      fecha_revision: "Día revisión de insumos",
      fecha_entrega: "Día entrega de insumos",
      obs_insumos: "Observaciones de los insumos",
      fin_insumos: "Insumos listos",
      referencia_id: "Referencia",
      cliente_id: "Cliente",
      tipo_prenda_id: "Descripción",
      created_at: "Fecha de ingreso",
      precio_u: "Precio unitario",
      precio_t: "Precio total",
      secuencia: "No. de secuencia en programación",
      obs_integracion: "Observaciones de integración",
      fin_integracion: "Integración lista",
      fecha_entrada: "Día recepción de insumos",
      programacion_id: "Programación"
    }
    keys.each do |key| 
      if modify.include? key.to_sym
        names.push modify[key.to_sym]
      else
        names.push key.capitalize
      end
    end
    return names
  end

  def keys_lote(lote)
    p = lote.programacion
    { 
      op: lote.op,
      cantidad: lote.cantidad,
      no_remision: lote.no_remision,
      no_factura: lote.no_factura,
      fecha_revision: lote.fecha_revision,
      fecha_entrega: lote.fecha_entrega,
      obs_insumos: lote.obs_insumos,
      fin_insumos: lote.fin_insumos ? "Sí": "No" ,
      referencia_id: lote.referencia.name,
      cliente_id: lote.cliente.name,
      tipo_prenda_id: lote.tipo_prenda.name,
      created_at: lote.created_at,
      precio_u: Money.new("#{lote.precio_u}00").format,
      precio_t: Money.new("#{lote.precio_t}00").format,
      secuencia: lote.secuencia,
      obs_integracion: lote.obs_integracion,
      fin_integracion: lote.fin_integracion ? "Sí": "No",
      fecha_entrada: lote.fecha_entrada,
      programacion_id: p.nil? ? "No tiene" : p.mes
    }
  end

  # Keys: Atributos que serán exportados
  # Value: Hash de valores de los atributos del lote
  def values_lote(keys, value)
    values = Array.new
    keys.each do |key|
      if value.include? key.to_sym
        values.push(value[key.to_sym])
      end
    end
    return values
  end
end

app/views/lotes/_cantidad_fields.html.erb
<%=f.input :cantidad, label: false, wrapper: :vertical_input_group,
input_html: { class: "cantidad#{n} input-sm", title: "color talla #{n + (n + 4)}", min: "0" } %>
<%=f.hidden_field :total_id, :value => !@totales_tallas.nil? ? @totales_tallas.fetch(n - 1) : 0,  
class: "total#{n}" %>
<%=f.hidden_field :categoria_id, :value => n %>
<%=f.hidden_field :_destroy %> 

app/views/lotes/_form.html.erb
<%
  place = nil
  if params[:action]=="edit"
    place = "form_edit_lote_response"
  else
    place = "form_new_lote_response"
  end
%>
<% action = params[:action] %>
<% url = action=="edit" || action=="update" ? lote_path(:place => place) : lotes_path(:place => place) %>

<%= simple_form_for(@lote, :url => url) do |f| %>
    <div class="box box-primary">
      <div class="box-header">
        <h3 class="box-title">
          <p>
            <% if !@lote.cliente.nil? %>
                <%= @lote.cliente.cliente %> -
            <% end %>
            <% if !@lote.referencia.nil? %>
                <%= @lote.referencia.referencia %>
            <% end %>
          </p>
        </h3>
        <div class="box-tools pull-right">
          <%= f.button :submit, :value => 'Aceptar', data: {:disable_with => "Guardando"}, class: 'btn btn-primary btn-sm', :id => "lote_guardar" %>
          <%= link_to 'Cancelar', "/#{params[:plc] || params[:lote][:plc]}", class: 'btn btn-default btn-sm' %>
        </div>
      </div>
      <div class="box-body">
        <%= f.error_notification %>
        <ul class="nav nav-tabs">
          <% if can? :integracion, Lote %>
              <li class="active"><a data-toggle="tab" href="#integracion">Integración</a></li>
          <% end %>

          <% if can? :insumos, Lote %>
              <li class=<%= (current_user.has_rol? :aux_insumos) ? "active" : "" %>>
                <a data-toggle="tab" href="#insumos">Insumos</a></li>
          <% end %>

          <% if can? :billing, Lote %>
              <li class=<%= (current_user.has_rol? :aux_facturacion) ? "active" : "" %>>
                <a data-toggle="tab" href="#facturacion">Facturación</a></li>
          <% end %>
        </ul>
        <div class="tab-content">

          <% if can? :integracion, Lote %>
              <div id="integracion" class="tab-pane fade in active">
                <% # Integración %>
                <%= render "form_zone_integracion", f: f %>
              </div>
          <% end %>

          <% if can? :insumos, Lote %>
              <div id="insumos" class="tab-pane fade <%= (current_user.has_rol? :aux_insumos) ? "in active" : "" %>">
                <% # Insumos %>
                <%= render "form_zone_insumos", f: f %>
              </div>
          <% end %>

          <% if can? :billing, Lote %>
              <div id="facturacion" class="tab-pane fade <%= (current_user.has_rol? :aux_facturacion) ? "in active" : "" %>">
                <% # Facturacion %>
                <%= render "form_zone_facturacion", f: f %>
              </div>
          <% end %>
        </div>
      </div>
      <% if params[:action].eql?("edit") || params[:action].eql?("update") %>
        <div class="box-footer">
          <div class="pull-right">
            <%= f.button :submit, :value => 'Aceptar', data: {:disable_with => "Guardando"}, class: 'btn btn-primary btn-sm', :id => "lote_guardar" %>
            <%= link_to 'Cancelar', "/#{params[:plc] || params[:lote][:plc]}", class: 'btn btn-default btn-sm' %>
          </div>
        </div>
      <% end %>
    </div>

    <% if can?(:cambio_estado, Lote) && (params[:action].eql?("new") || params[:action].eql?("create")) %>
        <div class="box box-warning">
          <div class="box-header">
            <h3 class="box-title">Datos del proceso</h3>
          </div>
          <div class="box-body">
            <%= f.fields_for :control_lotes, @control_lotes do |c| %>
                <%= render partial: 'control_lotes/form_fields', locals: {c: c, col: 4} %>
            <% end %>
          </div>
          <div class="box-footer">
            <div class="pull-right">
              <%= f.button :submit, :value => 'Aceptar', data: {:disable_with => "Guardando"}, class: 'btn btn-primary btn-sm', :id => "lote_guardar" %>
              <%= link_to 'Cancelar', "/#{params[:plc] || params[:lote][:plc]}", class: 'btn btn-default btn-sm' %>
            </div>
          </div>
        </div>
    <% end %>
    <!--____Fin detalle de estado_____________________________-->

    <%= f.hidden_field :plc, value: params[:plc] || params[:lote][:plc] %>
<% end %>
<% # Fin simple form %>

app/views/lotes/_form_zone_integracion.html.erb
<% company = session[:selected_company] ? "CAB" : "D&C" %>
<%= f.hidden_field :empresa, :value => company %>
<div style="margin-top: 20px;"></div>
<!--Otros roles Primera fila-->
<div class="row">
  <div class="col-lg-9">
    <div class="col-md-4" style="max-height: 90px;">
      <%= f.input :op, input_html: {data:{:url => lote_validate_op_path( @lote.id || 0)}, style: 'text-transform:uppercase;', autocomplete: 'off', autofocus: true} %>
    </div>
    <div class="col-md-4" style="max-height: 90px;">
      <%= f.input :referencia, input_html: {style: 'text-transform:uppercase;', autocomplete: 'off', value: @lote.referencia.nil? ? "" : @lote.referencia.referencia} %>
    </div>
    <div class="col-md-4" style="min-height: 90px; max-height: 90px;">
      <%= f.input :cliente, wrapper: :vertical_input_group do %>
          <%= f.input_field :cliente_id, class: "form-control", :collection => @clientes, :value_method => :id, :include_blank => "-- seleccione cliente --" %>
          <div class="input-group-btn">
            <%= link_to '...', new_cliente_path(:place => "form_lote_cliente"), {:remote => true, 'data-toggle' => "modal", 'data-target' => '#myModal', :class => "btn btn-primary", :title => "Nuevo cliente"} %>
          </div>
      <% end %>
    </div>
    <div class="col-md-4">
      <%= f.input :tipo_prenda_id, label: "Descripción", wrapper: :vertical_input_group do %>
          <%= f.input_field :tipo_prenda_id, class: "form-control", :collection => @tipos_prendas, :value_method => :id, :include_blank => "-- seleccione descripción --" %>
          <div class="input-group-btn">
            <%= link_to '...', new_tipo_prenda_path(:place => "form_lote_tipo_prenda"), {:remote => true, 'data-toggle' => "modal", 'data-target' => '#myModal', :class => "btn btn-primary", :title => "Nueva descripción"} %>
          </div>
      <% end %>
    </div>
    <div class="col-md-4">
      <%= f.association :programacion, as: "string", input_html: {:autocomplete => "off", :value => date_form_value(@lote), data: {calendar: "false"}} %>
    </div>
    <style type="text/css">
      .hide-calendar .ui-datepicker-calendar {
        display: none;
      }
    </style>
    <div class="col-md-4" style="padding-top:15px">
      <%= f.label :fin_integracion_true, label: "¿Tiene lista la integración?" %><br>
      <%= f.collection_radio_buttons :fin_integracion, [[true, 'Sí'], [false, 'No']], :first, :last, {item_wrapper_class: 'radio-inline', item_wrapper_tag: :div} %>
    </div>
  </div>
  <div class="col-lg-3">
    <%= f.input :obs_integracion, input_html: {:style => "height: 125px"}, :label => 'Notas de integración' %>
  </div>
</div>
<!--Otros roles Fin primera fila-->
<!--Otros roles Segunda fila-->
<hr>

<!--#########################################################################-->
<!--_________________________Detalle de cantidades___________________________-->
<!--#########################################################################-->
<div class="row">
  <div class="col-md-12">
    <h4>Cantidades por talla</h4>
    <span class="text-danger">
      <% if !@lote.errors[:colores_lotes].empty? %>
      Por favor ingrese el color y al menos una cantidad
      <% end %>
    </span>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="table-responsive">
      <!--Inicio de tabla-->
      <%= render "form_zone_detalle_cantidades", f: f %>
      <!--fin de tabla-->
    </div>
  </div>
</div>

app/views/lotes/edit.html.erb
<%= content_for :content_breadcrumb do %>
    <li><%= link_to params[:plc].capitalize, "/#{params[:plc]}" %></li>
    <li class="active"><%= link_to "Editar lote", edit_lote_path(@lote, :place => "form_edit_lote", :plc => params[:plc]) %></li>
<% end %>
<%= content_for :content_header do %>
    <h1>Editar lote</h1>
<% end %>
<%= content_for :title do
  "Editar lote"
end %>
<%= render 'form', lote: @lote %>

app/views/lotes/index.html.erb
<% content_for :title do %>
    Lotes
<% end %>
<%= content_for :content_header do %>
    <h1>
      Todos los lotes
      <small>Estos son todos los lotes de <%= session[:selected_company] ? "Cofecab" : "Diseños y camisas" %></small>
    </h1>
<% end %>
<%= content_for :content_breadcrumb do %>
    <li><%= link_to "Lotes", lotes_path %></li>
<% end %>
<% can_pri = can? :prices, Lote %>
<div class="box box-primary with-border" style="margin-top: 20px;">
  <div class="box-header">
    <h4 class="box-title">Lotes <span class="label label-primary"><%= Lote.where(:empresa => session[:selected_company] ? "CAB" : "D&C").count %></span></h4>
    <div class="box-tools pull-right">
      <% if can? :export, Lote %>
          <%= link_to options_export_lotes_path, :remote => true, :class => "btn-sm", :id => "exportar", :title => "Exportar excel" do %>
              <i class="fa fa-file-excel-o fa-2x" aria-hidden="true"></i>
          <% end %>
      <% end %>

      <% if can? :create, Lote %>
          <%= link_to new_lote_path(:plc => controller_name), :title => "Nuevo lote", :class => "btn-sm" do %>
              <%= content_tag :i, "", :class => "fa fa-plus fa-2x" %>
          <% end %>
      <% end %>
    </div>

  </div>
  <div class="box-body">
    <div class="nav-tabs-custom">
      <% active = cookies[:tab_active] || @estados.first.id %>
      <% active = active.to_i %>
      <ul class="nav nav-tabs">
        <li class="<%= "active" if 0 == active %>" data-url-tabs="<%= lotes_url(format: :js, state: 0) %>" data-id="<%= 0 %>">
          <%= link_to "Todos", "#all", data:{:toggle => "tab"} %>
        </li>
        <% @estados.each do |estado| %>
            <% id = estado.id %>
          <li class="<%= "active" if id == active %>" data-url-tabs="<%= lotes_url(format: :js, state: id) %>" data-id="<%= id %>">
            <%= link_to estado.name.capitalize, "##{estado.name.downcase}", data:{:toggle => "tab"} %>
          </li>
        <% end %>
      </ul>
      <div class="tab-content no-padding">
        <div class="tab-pane <%= "active" if 0 == active %>" id="all"></div>
        <% @estados.each do |estado| %>
            <div class="tab-pane <%= "active" if estado.id == active %>" id="<%= estado.name.downcase %>"></div>
        <% end %>
      </div>
    </div>
  </div>
  <div id="targets" data-padding="[<%= can_pri ? "1, 7" : "1" %>]" data-orderable="[1, 3, 4, 5<%= ", 7, 8" if can_pri  %>]"></div>
</div>

app/views/lotes/new.html.erb
<%= content_for :content_breadcrumb do %>
    <li><%= link_to "Lotes", lotes_path %></li>
    <li class="active"><%= link_to "Nuevo lote", new_lote_path(:plc => controller_name) %></li>
<% end %>
<%= content_for :content_header do %>
    <h1>Nuevo lote</h1>
<% end %>
<% content_for :title do
  "Nuevo lote"
end %>
    <%= render 'form', lote: @lote %>

app/views/lotes/options_export.js.erb
$("#myModal").html("<%= j render 'options_export' %>");
$("#myModal").modal("toggle");

app/views/lotes/show.html.erb
<script type="text/javascript">
    window.location.href="/lotes" 
</script>