config/routes.rb
Rails.application.routes.draw do

  get 'estadisticas', to: 'estadisticas#index'
  get "estadisticas/programaciones/detalles/:year/:month", to: "estadisticas#show_programaciones", as: :programaciones_show
  get "estadisticas/clientes/detalles/:year", to: "estadisticas#show_cliente", as: :clientes_show
  get "estadisticas/clientes/mes/:year_month", to: "estadisticas#show_month_cliente", as: :clientes_month_show
  namespace :estadisticas do
    get :clientes
    get :programaciones
  end

  # Rutas para las programaciones
  match 'programaciones/remove_from_programing/:month', to: 'programaciones#remove_from_programing', as: :remove_from_programing, via: [:post, :patch] # Para editar un atributo concreto; es patch
  get 'programaciones/program_table/:month', to: 'programaciones#program_table', as: :program_table
  get 'programaciones/modal_open/:month', to: 'programaciones#modal_open', as: :modal_open  # Leer recurso; es get
  get 'programaciones/options_export/:month', to: 'programaciones#options_export', as: :programacion_options_export
  resources :programaciones, only:[:index] do
    # Más información sobre collection http://guides.rubyonrails.org/routing.html#adding-collection-routes
    get :export_pdf, on: :collection
    get :export_excel, on: :member
    get :get_row, on: :collection
    patch :generate, on: :member # Editar una parte concreta, es patch
    patch :add_lotes_to_programing, as: :add_lotes, on: :collection # Para editar un atributo concreto; es patch
    patch :update_row_order, on: :collection
  end

  # Rutas de los usuarios
  devise_for :users
  resources :users, except: [:create] do
    post 'new' => 'users#create', as: :create, on: :collection
    patch :lock, on: :member
    patch :unlock, on: :member
  end

  # Rutas de los lotes
  resources :lotes do
    get :autocomplete_color_color, :on => :collection
    get :options_export, :on => :collection
    get :export_excel, :on => :collection
    get :view_details           # es método get, y parte de los lotes
    patch :cambio_estado        # Este es patch y debe pertenecer a los lotes
    patch :total_price, on: :member # esta es un patch y pertenece a los lotes
    patch :update_ingresara_a_planta, on: :member
    patch :update_programacion, on: :member
    resources :control_lotes do 
      patch :update_cantidad, on: :member
    end
    post :validate_op
  end

  resources :control_lotes do
    resources :seguimientos
  end

  # Otras rutas
  resources :sub_estados, :referencias, :tipos_prendas, :tallas, :roles, :clientes
  resources :calendario, except: :show
  resources :estados do
    patch :lock, on: :member
    patch :unlock, on: :member
  end
  # get "clientes/send_email" => 'clientes#send_email', :as => :send_email # debe pertenecer a los clientes y tener el id del cliente a quien se envía el correo

  get '/sobre-confecab', to: 'static_pages#about_confecab', as: :about_confecab
  get '/sobre-disenos-y-camisas', to: 'static_pages#about_dyc', as: :about_dyc
  # Inicio de la aplicación
  root :to => 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # http://guides.rubyonrails.org/routing.html#non-resourceful-routes
end

app/models/user.rb
=begin
AUTENTICACIÓN
Modelo para los usuarios. Tiene los módulos que se usan en devise para las acciones
=end
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :lockable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:login]
  attr_accessor :login

  # RELACIONES
  has_and_belongs_to_many :roles
  has_many :control_lotes, class_name: 'ControlLote', primary_key: 'id', foreign_key: 'resp_ingreso_id'
  has_many :control_lotes, class_name: 'ControlLote', primary_key: 'id', foreign_key: 'resp_salida_id'
  has_many :lotes, class_name: 'Lote', primary_key: 'id', foreign_key: 'respon_insumos_id'
  has_many :lotes, class_name: 'Lote', primary_key: 'id', foreign_key: 'respon_edicion_id'

  # Validaciones
  validates :name, :presence => {:message => "El nombre y apellido deben estar"}
  validates :email, 
            :presence => {:message => "Ingrese un correo electrónico"},
            :uniqueness => {
              :case_sensitive => false,
              :message => "Este correo ya existe"
            }
  validates :username,
            :numericality => { 
              only_integer: true,
              :greater_than_or_equal_to => 0,
              :message => "La cédula no es válida (Solo números y positivos)"
            },
            :uniqueness => {
              :case_sensitive => false,
              :message => "Esta cédula ya existe"
            }
  validates :rol_ids, :presence => {:message => "Por favor seleccione un permiso"}

  
  
  
  # MÉTODOS
  # Definir qué roles tiene un usuario
  def has_rol?(rol_sym)
    roles.any? { |r| r.name.underscore.to_sym == rol_sym }
  end
  
  #Metodo para iniciar con usuario o correo electrónico
  #Documentación para más información
  #https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign-in-using-their-username-or-email-address
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value",
      { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

end

app/controllers/users_controller.rb
=begin
CONTROLADOR DE USUARIOS (USERS)
Controlador independente del que devise usa para abrir sessions registrar usuarios y demás acciones. Esta clase
es para uso del administrador del sistema de modo que pueda gestionar los usuarios
=end
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :destroy, :update]
  

  # Validación de autorización
  load_and_authorize_resource
  def index
    respond_to do |format|
      format.html
      format.json {render json: users_json}
    end
  end

  def new
    @user = User.new
  end
  
  def show
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        flash[:success] = 'Usuario registrado con éxito.'
        format.html { redirect_to users_path }
        format.json  { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json  { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    if @user.id != 1
      if @user.destroy
        respond_to do |format|
          format.json  { head :no_content }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to users_path }
        flash[:danger] = "Este usuario no puede ser eliminado"
        format.json { head :conflict }
      end
    end
  end
  
  def edit
    respond_to do |format|
      format.js {render "show"}
    end
  end

  def update
    roles_user = RolesUser
    @rol = roles_user.where(:user_id => @user.id).update(:rol_id => params[:user][:rol_ids])
    if @rol
      @new_rol = roles_user.joins(:rol)
                  .where(user_id: params[:id])
                  .pluck("roles.name")
      respond_to do |format|
        format.js {render "show"}
      end
    end
  end

  # Bloquear los usuarios
  def lock
    user = User.find(params[:id])
    user.lock_access!(send_instructions: false)
    response_json(json: {message: "Usuario #{user.name} bloqueado. Ya no podrá acceder al sistema"})
  end

  # Desbloquear los usuarios
  def unlock
    user = User.find(params[:id])
    user.unlock_access!
    response_json(json: {message: "Usuario #{user.name} desbloqueado. Ya puede acceder al sistema"})
  end

  private

  def users_json
    lock = params[:lock?]
    @lock = true if lock == "true"
    @users = User.where("locked_at #{(@lock ? "IS NOT NULL" : "IS NULL")}")
    view_context.render(partial: "table", formats: :html)
  end

  # Respuesta con json
  def response_json(options)
    respond_to do |format|
      format.json{render options}
    end
  end

    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation, :name,
        :telefono, :remember_me, :rol_ids )
    end

    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="box box-primary">
  <%= simple_form_for @user, url: create_users_path do |f| %>
      <div class="box-body">
        <%= f.error_notification %>
        <div class="col-md-6">
          <%= f.input :email, required: true, autofocus: true, label: "Correo electrónico (Usuario de acceso)" %>
          <%= f.input :name, required: true, label: "Nombre y apellido" %>
          <%= f.input :telefono, label: "Teléfono" %>
        </div>

        <div class="col-md-6">
          <%= f.input :username, required: true, label: "Cédula (Usuario de acceso)" %>
          <%= f.input :password, required: true, hint: ("#{@minimum_password_length}
      characters minimum" if @minimum_password_length), label: "Contraseña" %>
          <%= f.input :password_confirmation, required: true, label: "Confirme contraseña" %>
          <%= f.input :rol_ids, :collection => Rol.all, :value_method => :id, label: "Tipo de permiso" %>
        </div>
      </div>
      <div class="box-body">
        <div class="box-tools pull-right">
          <%= f.button :submit, "Resgistrar", :class => "btn btn-primary btn-sm" %>
          <%= link_to 'Cancelar', users_path, class: "btn btn-sm btn-default" %>
        </div>
      </div>
  <% end %>
</div>

app/views/users/_form_permission.html.erb
<script type="text/javascript">
	$("#cancelar").click(function(e){
		$("#edit_permission").children().remove();
		$("#edit_permission").hide();
		e.preventDefault(); 
	});
</script>
<%= simple_form_for @user, remote: true do |f|%>
    <%= f.error_notification %>
    <div class="text-left col-sm-6">
    	<%= f.input :rol_ids, :collection => Rol.all, :value_method => :id, label: false, class: "input-sm"%>
	</div>
	<div class="text-right col-sm-6">
  		<%= f.button :submit, "Aceptar", class: "btn-sm" %>
  		<%= link_to 'Cancelar', "#", class:"btn btn-sm btn-outline btn-primary", :id => "cancelar"%>
    </div>
<%end%>

app/views/users/_show.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h4 class="modal-title" id="myModalLabel"><%=@user.name%></h4>
    </div>
    <div class="modal-body">
      <table class="table">
        <tbody>
          <tr>
            <th class="col-sm-6">Teléfono:</th>
            <td class="col-sm-6"><%= @user.telefono %></td>
          </tr>
          <tr>
            <th class="col-sm-6">Correo:</th>
            <td class="col-sm-6"><%= @user.email %></td>
          </tr>
          <tr>
            <th class="col-sm-6">Cédula:</th>
            <td class="col-sm-6"><%= @user.username %></td>
          </tr>
          <tr>
            <th class="col-sm-6">Tipo de permiso:</th>
            <td class="col-sm-6">
              <p class="text-left col-sm-6" id="current_rol">
              <% @user.roles.each do |ru| %>
                <%=ru.name.capitalize%>
              <%end%>
              </p>
              <p class="text-right col-sm-6">
              <%if can? :update, User%>
                <%if @user.id != 1%>
                  <%=link_to edit_user_path(@user), :title => "Cambiar permiso", remote: true do%>
                    <%=content_tag :i, "", :class => "fa fa-pencil"%>
                  <%end%>
                <%end%>
              <%end%>
              </p>
            </td>
          </tr>
          <tr>
            <td colspan="2" id="edit_permission" style="display: none;">
            </td>
          </tr>
          <tr>
            <th class="col-sm-6">Último ingreso:</th>
            <td class="col-sm-6">
            <% if !@user.current_sign_in_at.nil? %>
            <%= I18n::localize(@user.current_sign_in_at, :format => "%d de %B a las %I:%M %p" ) %>
            <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
    </div>
  </div>
</div>

app/views/users/_table.html.erb
<table class="table table-striped table-bordered">
  <thead>
  <tr>
    <th></th>
    <th></th>
    <th title="Nombre">Nombre</th>
    <th title="Cédula">Cédula</th>
    <th title="Correo">Correo</th>
    <th title="Teléfono">Teléfono</th>
  </tr>
  </thead>
  <tbody>
  <% if @users.empty? %>
      <tr>
        <td colspan="<%= can?(:manage, User) ? "6" : "5" %>">No hay datos disponibles</td>
      </tr>
  <% else %>
      <% @users.each do |user| %>
          <tr>
            <td class="text-center">
              <%= link_to user_path(user), {:remote => true, :title => "Ver detalles"} do %>
                  <%= content_tag :i, "", :class => "fa fa-list-alt" %>
              <% end %>
            </td>
            <td class="text-center">
              <% lock = user.access_locked? %>
              <% if can? :lock, user %>
                  <%= link_to (@lock ? unlock_user_path(user) : lock_user_path(user)), data: {action: "delete"},
                              method: :patch, class: "text-red", :title => ((@lock ? "Desbloquear" : "Bloquear ")), remote: true do %>
                      <%= content_tag :i, "", :class => (@lock ? "fa fa-unlock" : "fa fa-lock") %>
                  <% end %>
              <% end %>
            </td>
            <td title="Nombre"><%= user.name %></td>
            <td title="Cédula"><%= user.username %></td>
            <td title="Correo"><%= user.email %></td>
            <td title="Teléfono"><%= user.telefono %></td>
          </tr>
      <% end %>
  <% end %>
  </tbody>
</table>

app/views/users/index.html.erb
<%= content_for :content_breadcrumb do %>
    <li class="active"><%= link_to "Usuarios", users_path %></li>
<% end %>
<%= content_for :content_header do %>
    <h1>Todos los usuarios del sistema
      <small>Agregue un nuevo usuario con un tipo de permiso para que pueda acceder al sistema</small>
    </h1>
<% end %>
<% content_for :title do
  "Usuarios"
end %>
<div class="box box-primary with-border">
  <div class="box-header">
    <h3 class="box-title">Usuarios</h3>
    <div class="box-tools pull-right">
      <% if can? :create, User %>
          <%= link_to new_user_path, :title => "Nuevo usuario" do %>
              <%= content_tag :i, "", :class => "fa fa-plus fa-2x" %>
          <% end %>
      <% end %>
    </div>
  </div>
  <div class="box-body table-responsive">
    <div class="nav-tabs-custom">
      <ul class="nav nav-tabs">
        <li class="active" data-url="<%= users_path(format: :json, lock?: false) %>">
          <%= link_to "Activos", "#unlock", data: {:toggle => "tab"} %>
        </li>
        <li class="" data-toggle="tab" data-url="<%= users_path(format: :json, lock?: true) %>">
          <%= link_to "Bloqueados", "#lock", data: {:toggle => "tab"} %>
        </li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="unlock"></div>
        <div class="tab-pane" id="lock"></div>
      </div>
    </div>
  </div>
</div>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
</div>

app/views/users/new.html.erb
<%= content_for :content_breadcrumb do %>
    <li><%= link_to "Usuarios", users_path %></li>
    <li class="active"><%= link_to "Nuevo usuario", new_user_path %></li>
<% end %>
<%= content_for :content_header do %>
    <h1>Nuevo usuario</h1>
<% end %>
<%content_for :title do "Nuevo usuario" end%>
    <%= render 'form'%>
 

app/views/users/show.js.erb
<%if params[:action].eql?("show")%>
	$("#myModal").html("<%= escape_javascript(render 'users/show') %>");
	$("#myModal").modal('toggle');
<%elsif params[:action].eql?("edit")%>
	$("#edit_permission").html("<%= j render 'form_permission'%>");
	$("#edit_permission").slideDown(600);
<%elsif params[:action].eql?("update")%>
	$("#edit_permission").children().slideUp(600);
	$("#edit_permission").hide();
	console.log("<%=@new_rol.last.capitalize%>");
	$("#current_rol").text("<%=@new_rol.last.capitalize%>")
<%end%>