config/routes.rb
Rails.application.routes.draw do

  get 'estadisticas', to: 'estadisticas#index'
  get "estadisticas/programaciones/detalles/:year/:month", to: "estadisticas#show_programaciones", as: :programaciones_show
  get "estadisticas/clientes/detalles/:year", to: "estadisticas#show_cliente", as: :clientes_show
  get "estadisticas/clientes/mes/:year_month", to: "estadisticas#show_month_cliente", as: :clientes_month_show
  namespace :estadisticas do
    get :clientes
    get :programaciones
  end

  # Rutas para las programaciones
  match 'programaciones/remove_from_programing/:month', to: 'programaciones#remove_from_programing', as: :remove_from_programing, via: [:post, :patch] # Para editar un atributo concreto; es patch
  get 'programaciones/program_table/:month', to: 'programaciones#program_table', as: :program_table
  get 'programaciones/modal_open/:month', to: 'programaciones#modal_open', as: :modal_open  # Leer recurso; es get
  get 'programaciones/options_export/:month', to: 'programaciones#options_export', as: :programacion_options_export
  resources :programaciones, only:[:index] do
    # Más información sobre collection http://guides.rubyonrails.org/routing.html#adding-collection-routes
    get :export_pdf, on: :collection
    get :export_excel, on: :member
    get :get_row, on: :collection
    patch :generate, on: :member # Editar una parte concreta, es patch
    patch :add_lotes_to_programing, as: :add_lotes, on: :collection # Para editar un atributo concreto; es patch
    patch :update_row_order, on: :collection
  end

  # Rutas de los usuarios
  devise_for :users
  resources :users, except: [:create] do
    post 'new' => 'users#create', as: :create, on: :collection
    patch :lock, on: :member
    patch :unlock, on: :member
  end

  # Rutas de los lotes
  resources :lotes do
    get :autocomplete_color_color, :on => :collection
    get :options_export, :on => :collection
    get :export_excel, :on => :collection
    get :view_details           # es método get, y parte de los lotes
    patch :cambio_estado        # Este es patch y debe pertenecer a los lotes
    patch :total_price, on: :member # esta es un patch y pertenece a los lotes
    patch :update_ingresara_a_planta, on: :member
    patch :update_programacion, on: :member
    resources :control_lotes do 
      patch :update_cantidad, on: :member
    end
    post :validate_op
  end

  resources :control_lotes do
    resources :seguimientos
  end

  # Otras rutas
  resources :sub_estados, :referencias, :tipos_prendas, :tallas, :roles, :clientes
  resources :calendario, except: :show
  resources :estados do
    patch :lock, on: :member
    patch :unlock, on: :member
  end
  # get "clientes/send_email" => 'clientes#send_email', :as => :send_email # debe pertenecer a los clientes y tener el id del cliente a quien se envía el correo

  get '/sobre-confecab', to: 'static_pages#about_confecab', as: :about_confecab
  get '/sobre-disenos-y-camisas', to: 'static_pages#about_dyc', as: :about_dyc
  # Inicio de la aplicación
  root :to => 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # http://guides.rubyonrails.org/routing.html#non-resourceful-routes
end

app/models/control_lote.rb
class ControlLote < ApplicationRecord
  has_many :seguimientos, :dependent => :destroy
  belongs_to :lote, optional: true
  belongs_to :estado
  belongs_to :sub_estado, optional: true
  belongs_to :resp_ingreso_id, class_name: 'User', foreign_key: 'resp_ingreso_id'
  belongs_to :resp_salida_id, class_name: 'User', foreign_key: 'resp_salida_id', 
  optional: true
  
  # Validaciones
  validates :estado, :fecha_ingreso, presence: true

  scope :prev, ->(id, lote_id) { where("id < ? and lote_id = ?", id, lote_id).last }
  scope :next, ->(control) { where("id > ? and lote_id = ?", control, control.lote).first }

  # Métodos
  def sub_or_process
    if sub_estado_id > 0
      self.sub_estado.sub_estado.capitalize
    else
      self.estado.estado.capitalize
    end
  end

  # Get para la última cantidad
  def cantidad_last
    last = self.seguimientos.last
    return last.cantidad if last
    0
  end

  def sub_estado_id=(val)
    val = val.strip.eql?("") ? "0" : val
    write_attribute(:sub_estado_id, val)
  end

  def date_range
    date1 = self.fecha_ingreso
    date2 = self.fecha_salida
    if !date2.nil?
      with_month = nil
      if date1.strftime("%m") == date2.strftime("%m")
        with_month = I18n::l(date1, format: "%d")
      else
        with_month = I18n::l(date1, format: "%d de %b")
      end
      "#{with_month} - #{I18n::l(date2, format: "%d de %b")}"
    else
      I18n::l(date1, format: "%d de %b")
    end
  end

  def fecha_ingreso_input
    return  I18n::localize( self.fecha_ingreso, :format => "%Y-%m-%d %H:%M:%S") if !self.fecha_ingreso.nil?
    I18n::localize( Time.zone.utc_to_local(Time.new) + 60, :format => "%Y-%m-%d %H:%M:%S")
  end

  def self.hash_ids
    result = ControlLote.select("lote_id, fecha_ingreso").where("control_lotes.fecha_ingreso = (SELECT MIN(fecha_ingreso) FROM control_lotes cl GROUP BY lote_id HAVING cl.lote_id = control_lotes.lote_id)")
    hash_ids = Hash.new
    result.each do |r|
      hash_ids[r.lote_id] = r.fecha_ingreso
    end
    return hash_ids
  end

  # Retorna un hash con opciones de la resta de los días
  def self.date_operated(date_initial, date_final)    
    {
      :days => days_absolute(date_initial, date_final)
    }
  end

  def self.after_before(lote)
    amount_lote = lote.cantidad
    control_lotes = lote.control_lotes.sum(:cantidad)
    if amount_lote < control_lotes
      res = control_lotes - amount_lote
      return "Sobran #{res}"
    elsif amount_lote > control_lotes
      res = amount_lote - control_lotes
      return "Faltan #{res}"
    else
      return nil
    end
  end

  private
    # Parametros
    # d1: Día inicial 
    # d2: Dia final
    # return: Días absolutos entre dos fechas
    def self.days_absolute(d1, d2)
      di = d1 + 1.day 
      di = Time.local(di.year, di.month, di.day)
      df = Time.local(d2.year, d2.month, d2.day)
      ((df - di) / (24 * 60 * 60)).ceil + 2
    end
end

app/controllers/control_lotes_controller.rb
=begin
  CONTROLADOR DE CONTROL LOTES
Todas las acciones a la vista de acuerdo con el paradigma MVC
Este controlador es dependiente del controlador de los lotes y representa el ciclo de producción del lote
Todos los procesos que el lote vive el lote deben tener un registro mediante este controlador
=end
class ControlLotesController < ApplicationController
  #Solicitar prueba de permisos antes de cargar cualquier acción
  load_and_authorize_resource
  before_action :set_lote
  before_action :collection_control_lotes, only: [:index, :show]
  before_action :data_from_tracking, only: [:index, :show]
  before_action :set_control_lotes, only: [:edit, :update, :update_cantidad, :destroy]
  before_action :sub_estados, only: [:new, :edit]

  # GET /control_lotes
  # GET /control_lotes.json
  def index
  end

  def show
    params[:plc] = params[:plc] || 'lotes'
    render action: :index
  end

  def new
    @control_lote = ControlLote.new
  end

  def show
    render action: :index
  end

  def create
    respond_to do |format|
      last_state_lote = @lote.control_lotes.last
      @control_lote = @lote.control_lotes.new(control_lote_params)
      if @control_lote.save
        Seguimiento.seguimientos_status_change(@lote.cantidad, @control_lote, current_user, "cambio_estado")
        last_state_lote.update(:resp_salida_id => current_user,
                               :fecha_salida => control_lote_params[:fecha_ingreso])
        format.html { redirect_to lote_control_lotes_path(:plc => params[:control_lote][:plc]) }
        flash[:success] = "Proceso nuevo registrado"
        format.json { render :index, status: :ok }
      else
        sub_estados
        format.html { render :new }
        format.json { render json: @control_lote.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @control_lote.update(control_lote_params)
        format.html { redirect_to lote_control_lotes_path(:plc => params[:control_lote][:plc]) }
        flash[:success] = "Proceso actualizado correctamente"
      else
        sub_estados
        format.html { render :edit, :plc => params[:control_lote][:plc] }
        format.json { render json: @control_lote.errors, status: :unprocessable_entity }
      end
    end
  end

  # Para eliminar un proceso se valida que no sea el único existente para el lote. Después de esto se actualizan
  # los seguimientos del anterior proceso y el proceso anterior para que todo pueda ser como antes de que se creara
  # el proceso que se va a eliminar
  def destroy
    data = {}
    status = ""
    if @lote.control_lotes.count > 1
      set_prev_seguimiento
      prev_control
      @id = @control_lote.id
      @control_lote.destroy
      data = {status: :ok}
    else
      # La petición ha sido aceptada para procesamiento, pero este no ha sido completado. La petición eventualmente
      # pudiere no ser satisfecha, ya que podría ser no permitida o prohibida cuando el procesamiento tenga lugar.
      data = {status: :accepted, json: "No se puede eliminar el único registro del ciclo para el lote"}
    end
    respond_to do |format|
      format.js { render :destroy, data }
    end
  end

  def update_cantidad
    cantidad_params = params.require(:control_lote).permit(:cantidad)
    respond_to do |format|
      if @control_lote.update(cantidad_params)
        after = ControlLote.after_before @lote
        format.json { render json: {
            total: @lote.control_lotes.sum(:cantidad),
            after: after
        }, status: :ok }
      else
        format.json { render json: "No se puede procesar", status: :unprocessable_entity }
      end
    end
  end

  private
  def control_lote_params
    params.require(:control_lote).permit(:fecha_ingreso, :estado_id, :sub_estado_id,
                                         :observaciones).merge(resp_ingreso_id: current_user)
  end

  def set_lote
    @lote = Lote.find(params[:lote_id])
    @control = @lote.control_lotes.last
  end

  def set_control_lotes
    @control_lote = @lote.control_lotes.find(params[:id])
  end

  def sub_estados
    @sub_estados = SubEstado.all
  end

  def collection_control_lotes
    company = session[:selected_company]
    @control_lotes = @lote.control_lotes
    @user = {}
    @users = User.select("id, name").each { |e| @user[e.id] = e.name }
  end

  def data_from_tracking
    @seguimiento = Seguimiento.new
  end

  def set_prev_seguimiento
    this = ControlLote
    c_prev = this.prev(@control_lote, @control_lote.lote)
    prev_seguimientos = c_prev.is_a?(this) ? c_prev.seguimientos : nil
    if prev_seguimientos
      if prev_seguimientos.any?
        prev_seguimientos.where(reproceso: true).update(proceso: true, reproceso: false)
        last_segu = prev_seguimientos.last
        last_segu.update(cantidad: @control_lote.cantidad_last + last_segu.cantidad, fecha_salida: nil)
      end
    end
  end

  def prev_control
    @control = ControlLote.prev(@control_lote, @control_lote.lote)
    @control.update(fecha_salida: nil, resp_salida_id: nil) if @control_lote == @lote.control_lotes.last
  end
end

app/helpers/control_lotes_helper.rb
module ControlLotesHelper
  # Sub proceso del historial
  # sub_process(id_sub_proceso)
  def sub_process(sub_process)
    if sub_process
      @sub_estado[sub_process.id].upcase
    end
  end

  # Responsable de salida del proceso
  # respon_exit(id_responsable)
  def respon_exit(respon_exit)
    if respon_exit
      @user[respon_exit.id]
    end
  end


  def days(day1, day2)
    if !day2.nil?
      ControlLote.date_operated(day1, day2)[:days]
    else
      "-"
    end
  end

  def set_colspan(pref)
    if !can?(:update, ControlLote)
      pref -= 1
    end
    if !can?(:destroy, ControlLote)
      pref -= 1
    end
    return pref
  end

  def fecha_ingreso_input
    return @control_lote.fecha_ingreso_input if !@control_lote.nil?
    Time.zone.utc_to_local(Time.new) + 60
  end

  # wip_tracing: Definir si el campo para modificar la cantidad en este proceso debe o no aparecer
  def wip_tracing(control_lote)
    @control_lote = control_lote
    if control_lote.estado.pasa_manual
      arrows
    else
      "<span>#{control_lote.cantidad_last}</span>".html_safe
    end
  end

  private

  def arrows
    content_tag :div, "", class: "row" do
      down + amount + up
    end
  end

  def up
    link_to new_control_lote_seguimiento_path(@control_lote, process: false), data:{html: true, toggle: "popover#{@control_lote.id}2", placement: "top"},
            remote: true, :class => "btn btn-sm margin-r-5" do
      content_tag :i, "", :class => "fa fa-arrow-up"
    end
  end

  def down
    link_to new_control_lote_seguimiento_path(@control_lote, process: true),data:{html: true, toggle: "popover#{@control_lote.id}1", placement: "bottom"},
            remote: true, :class => "btn btn-sm margin-r-5" do
      content_tag :i, "", :class => "fa fa-arrow-down"
    end
  end

  def amount
    content_tag :span, @control_lote.cantidad_last, :class => "margin-r-5"
  end
end

app/views/control_lotes/_button_cambio_estado.html.erb
<% next_estado =  @lote.control_lotes.last.estado.next %>
<% if next_estado %>
    <%= link_to lote_cambio_estado_path(@lote, :btn => next_estado.id, :plc => params[:plc]), data:{ action: "cambio_estado" },
                remote: true, method: "PATCH", :class => "btn btn-primary" do %>
        <i class='fa fa-fast-forward fa-fw' aria-hidden='true'></i>
        <%= next_estado.nombre_accion %>
    <% end %>
<% end %>

app/views/control_lotes/_form.html.erb
<div class="box box-primary">
	<%= simple_form_for [@lote, @control_lote] do |f|%>
		<div class="box-body row">
			<div class="col-md-6">
        <div class="well">
          <table class="table table-bordered table-striped">
            <tbody>
            <tr>
              <th>Referencia:</th>
              <td><%= @lote.referencia.name %></td>
            </tr>
            <tr>
              <th>OP:</th>
              <td><%= @lote.op %></td>
            </tr>
            <tr>
              <th colspan="2" class="text-center">Datos del proceso actual</th>
            </tr>
            <tr>
              <th>Proceso actual:</th>
              <td><%= @control.estado.name.upcase %></td>
            </tr>
            <tr>
              <th>Proceso adicional:</th>
              <td>
                <% sub_estado = @control.sub_estado %>
                <%= sub_estado.nil? ? "No tiene proceso" : sub_estado.name.upcase %>
              </td>
            </tr>
            <tr>
              <th>Días en este proceso:</th>
              <td><%= days @control.fecha_ingreso, Time.new %></td>
            </tr>
            <tr>
              <th>Observaciones:</th>
              <td><%= @control.observaciones %></td>
            </tr>
            <tr>
              <th>Ingresado por:</th>
              <td><%= @control.resp_ingreso_id.name.upcase %></td>
            </tr>
            </tbody>
          </table>
        </div>
			</div>
			<div class="col-md-6">
				<%= render partial: 'form_fields', locals: { c: f, col: 12 } %>
			</div>
		</div>
		<div class="box-footer">
			<div class="box-tools pull-right">
				<%= link_to "Regresar", lote_control_lotes_path(:plc => plc) %>
				<%= f.button :button, :class => "btn btn-primary btn-sm" do %>
					<i class="fa fa-floppy-o fa-fw" aria-hidden="true"></i>
					Guardar
				<% end %>
			</div>

		</div>
		<%= f.hidden_field :plc, value: params[:plc] || params[:control_lote][:plc] %>
	<% end %>
</div>

app/views/control_lotes/_form_fields.html.erb
<div class="col-md-<%= col %>">
  <%= c.input :fecha_ingreso, as: "string", 
  input_html: {:value => fecha_ingreso_input },
  readonly: true, label: 'Entró a este proceso el día'  %>
</div>
<div class="col-md-<%= col %>">
  <%= c.association :estado, label: 'Parte del proceso', collection: Estado.active, :include_blank => true %>
</div>
<% # Sección del subestado %>
<div class="col-md-<%= col %>">
  <%= c.input :sub_estado, :label => 'Proceso adicional',  wrapper: :vertical_input_group do %>
  <% # form nuevo  %>
  <%= c.input_field  :sub_estado_id, class: "form-control",
  :collection => @sub_estados, :value_method => :id, 
  :include_blank =>  true %>

  <div class="input-group-btn">
    <%= link_to '...', new_sub_estado_path(:place => "form_lote_sub_estado"),
    {:remote => true, :class => "btn btn-primary", :title => "Nuevo proceso"} %>
  </div>
  <% end %>
</div>
<div class="col-md-12">
  <%= c.input :observaciones %>
</div>

app/views/control_lotes/_row.html.erb
<% this = ControlLote %>
<% seguimiento = Seguimiento %>
<% update_seguimiento = can? :update, seguimiento %>
<% read_seguimiento = can? :read, seguimiento %>
<tr data-id="<%= control_lote.id %>">
  <% if can? :update, this %>
      <td>
        <%= link_to edit_lote_control_lote_path(@lote, control_lote, :plc => params[:plc]) do %>
            <i class="fa fa-pencil" aria-hidden="true"></i>
        <% end %>
      </td>
  <% end %>
  <% if can? :destroy, this %>
      <td>
        <%= link_to lote_control_lote_path(@lote, control_lote, :plc => params[:plc]),
                    data: {:confirm => "¿Esta seguro de eliminar este proceso?", action: "delete"}, remote: true, method: "delete" do %>
            <i class="fa fa-trash text-red" aria-hidden="true"></i>
        <% end %>
      </td>
  <% end %>
  <td title="Proceso externo o interno"><%= control_lote.sub_or_process %></td>
  <td title="Fecha de ingreso" data-date="true"><%= control_lote.date_range %></td>
  <td title="Responsable de ingreso"><%= control_lote.resp_ingreso_id.name %></td>
  <td title="Responsable de salida"><%= respon_exit control_lote.resp_salida_id %></td>
  <td title="Días en proceso"><%= days control_lote.fecha_ingreso, control_lote.fecha_salida %></td>
  <td title="Observaciones"><%= control_lote.observaciones %></td>
  <% if update_seguimiento or read_seguimiento %>
      <td class="no-padding text-center">
        <%= update_seguimiento ? wip_tracing(control_lote) : control_lote.cantidad_last %>
      </td>
  <% end %>
</tr>

app/views/control_lotes/cambio_estado.js.erb
<%
@seguimiento = Seguimiento.new
@user = {}
@users = User.select("id, name").each{ |e|  @user[e.id] = e.name}
prev = ControlLote.prev(@control, @lote)
%>

$("table > tbody > tr").last().replaceWith("<%= j render 'control_lotes/row', control_lote: prev%>");
$("table > tbody").append("<%= j render 'control_lotes/row', control_lote: @control%>");
$("a[data-action='cambio_estado']").replaceWith("<%= j render 'control_lotes/button_cambio_estado' %>");

app/views/control_lotes/destroy.js.erb
<%
@seguimiento = Seguimiento.new
@user = {}
@users = User.select("id, name").each{ |e|  @user[e.id] = e.name}
%>
console.log($("tr[data-id='<%= @id %>']"));
<% if @control.is_a?(ControlLote) %>
$("tr[data-id='<%= @id %>']").prev().replaceWith("<%= j render 'control_lotes/row', control_lote: @control%>");
<% else %>
$("tr[data-id='<%= @id %>']").remove();
<% end %>
btn_cambio = $("a[data-action='cambio_estado']");
button = "<%= j render 'control_lotes/button_cambio_estado' %>";
if(btn_cambio.length > 0) {
    btn_cambio.replaceWith(button);
}else{
    $("table").closest(".box").next().children().append(button);
}

app/views/control_lotes/edit.html.erb
<% plc =  params[:plc] || params[:control_lote][:plc] %>
<%= content_for :content_breadcrumb do %>
    <li><%= link_to plc.capitalize, "/#{plc}" %></li>
    <li><%= link_to "Ciclo de producción", lote_control_lotes_path(@lote, @control_lotes, :plc => plc) %></li>
    <li class="active"><%= link_to "Editar proceso", edit_lote_control_lote_path(@lote, @control_lote, :plc => plc) %></li>
<% end %>
<%= content_for :content_header do %>
    <h1>Editar proceso</h1>
<% end %>
<%= render partial: 'form',  locals: {control_lote: @control_lote, plc: plc} %>

app/views/control_lotes/index.html.erb
<% referencia = @lote.referencia.referencia %>
<% lote = Lote %>
<% this = ControlLote %>
<% seguimiento = Seguimiento %>
<% update_seguimiento = can? :update, seguimiento %>
<% read_seguimiento = can? :read, seguimiento %>
<% content_for :title do %>
    Historial del lote <%= referencia %>
<% end %>
<%= content_for :content_header do %>
    <h1>
      Ciclo de
      produccion <%= can?(:update, lote) ? link_to(referencia, edit_lote_path(@lote, plc: params[:plc])) : referencia %>
      <small></small>
    </h1>
<% end %>
<%= content_for :content_breadcrumb do %>
    <li><%= link_to params[:plc].capitalize, "/#{params[:plc]}" %></li>
    <li><%= link_to "Ciclo de producción", lote_control_lotes_path(@lote, @control_lote, :plc => params[:plc]) %></li>
<% end %>
<div class="box box-primary with-border">
  <div class="box-header">
    <h4 class="box-title">Procesos</h4>
    <% if can? :create, this %>
        <div class="box-tools">
          <%= link_to new_lote_control_lote_path(@lote, :plc => params[:plc]), :title => 'Proceso nuevo' do %>
              <i class="fa fa-plus fa-2x" aria-hidden="true"></i>
          <% end %>
        </div>
    <% end %>
  </div>
  <div class="box-body table-responsive">
    <table class="table table-striped table-bordered">
      <thead>
      <tr class="bg-primary">
        <th colspan="<%= set_colspan 5 %>">REFERENCIA: <%= @lote.referencia.referencia %></th>
        <th colspan="<%= update_seguimiento ? "5" : "4" %>">OP: <%= @lote.op %></th>
      </tr>
      <tr class="bg-info">
        <% if can?(:update, this) || can?(:destroy, this) %>
            <th colspan="<%= set_colspan 2 %>"></th>
        <% end %>
        <th>Proceso</th>
        <th class="col-xs-2">Ingreso-Salida</th>
        <th class="col-xs-2">Ingresado por</th>
        <th class="col-xs-2">Salida por</th>
        <th>Días</th>
        <th class="col-xs-3">Observaciones</th>
        <% if update_seguimiento or read_seguimiento %>
            <th>Cantidades</th>
        <% end %>
      </tr>
      </thead>
      <tbody>
      <% @control_lotes.each do |control_lote| %>
          <%= render "row", control_lote: control_lote %>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="box-footer">
    <div class="box-tools pull-right">
      <strong>Cantidad total:</strong> <span><%= @lote.cantidad %></span> <br>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-offset-9 col-md-3 text-right">
    <%= link_to "Regresar", "/#{params[:plc]}" %>
    <% if can? :cambio_estado, lote %>
        <%= render "button_cambio_estado" %>
    <% end %>
  </div>
</div>

app/views/control_lotes/index.js.erb
$("#myModal").html("<%= j render 'index'%>");
$("#myModal").modal("toggle");

app/views/control_lotes/new.html.erb
<% plc =  params[:plc] || params[:control_lote][:plc] %>
<%= content_for :content_breadcrumb do %>
    <li><%= link_to plc.capitalize, "/#{plc}" %></li>
    <li><%= link_to "Ciclo de producción", lote_control_lotes_path(@lote, @control_lotes, :plc => plc) %></li>
    <li class="active"><%= link_to "Nuevo proceso", new_lote_control_lote_path(:plc => plc) %></li>
<% end %>
<%= content_for :content_header do %>
    <h1>Nuevo proceso</h1>
<% end %>
<%= render partial: 'form',  locals: {control_lote: @control_lote, plc: plc} %>