config/routes.rb
Rails.application.routes.draw do

  get 'estadisticas', to: 'estadisticas#index'
  get "estadisticas/programaciones/detalles/:year/:month", to: "estadisticas#show_programaciones", as: :programaciones_show
  get "estadisticas/clientes/detalles/:year", to: "estadisticas#show_cliente", as: :clientes_show
  get "estadisticas/clientes/mes/:year_month", to: "estadisticas#show_month_cliente", as: :clientes_month_show
  namespace :estadisticas do
    get :clientes
    get :programaciones
  end

  # Rutas para las programaciones
  match 'programaciones/remove_from_programing/:month', to: 'programaciones#remove_from_programing', as: :remove_from_programing, via: [:post, :patch] # Para editar un atributo concreto; es patch
  get 'programaciones/program_table/:month', to: 'programaciones#program_table', as: :program_table
  get 'programaciones/modal_open/:month', to: 'programaciones#modal_open', as: :modal_open  # Leer recurso; es get
  get 'programaciones/options_export/:month', to: 'programaciones#options_export', as: :programacion_options_export
  resources :programaciones, only:[:index] do
    # Más información sobre collection http://guides.rubyonrails.org/routing.html#adding-collection-routes
    get :export_pdf, on: :collection
    get :export_excel, on: :member
    get :get_row, on: :collection
    patch :generate, on: :member # Editar una parte concreta, es patch
    patch :add_lotes_to_programing, as: :add_lotes, on: :collection # Para editar un atributo concreto; es patch
    patch :update_row_order, on: :collection
  end

  # Rutas de los usuarios
  devise_for :users
  resources :users, except: [:create] do
    post 'new' => 'users#create', as: :create, on: :collection
    patch :lock, on: :member
    patch :unlock, on: :member
  end

  # Rutas de los lotes
  resources :lotes do
    get :autocomplete_color_color, :on => :collection
    get :options_export, :on => :collection
    get :export_excel, :on => :collection
    get :view_details           # es método get, y parte de los lotes
    patch :cambio_estado        # Este es patch y debe pertenecer a los lotes
    patch :total_price, on: :member # esta es un patch y pertenece a los lotes
    patch :update_ingresara_a_planta, on: :member
    patch :update_programacion, on: :member
    resources :control_lotes do 
      patch :update_cantidad, on: :member
    end
    post :validate_op
  end

  resources :control_lotes do
    resources :seguimientos
  end

  # Otras rutas
  resources :sub_estados, :referencias, :tipos_prendas, :tallas, :roles, :clientes
  resources :calendario, except: :show
  resources :estados do
    patch :lock, on: :member
    patch :unlock, on: :member
  end
  # get "clientes/send_email" => 'clientes#send_email', :as => :send_email # debe pertenecer a los clientes y tener el id del cliente a quien se envía el correo

  get '/sobre-confecab', to: 'static_pages#about_confecab', as: :about_confecab
  get '/sobre-disenos-y-camisas', to: 'static_pages#about_dyc', as: :about_dyc
  # Inicio de la aplicación
  root :to => 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # http://guides.rubyonrails.org/routing.html#non-resourceful-routes
end

app/models/estado.rb
=begin
Estos son los procesos principales por los que los lotes del sistema van a pasar
Son administrados por un root del sistema y son vitales para el funcionamiento del mismo.
=end
class Estado < ApplicationRecord
  has_many :control_lotes

  #Validaciones
  validates :secuencia, uniqueness: true
  validates :pasa_cantidad, :facturar, inclusion: {in: [true, false]}
  validates :estado, :nombre_accion, :color, :color_claro, :secuencia, presence: true
  validate :facturar_al, :max_percent_new, if: '!facturar_al.nil?', on: :create
  validate :facturar_al, :max_percent_update,if: '!facturar_al.nil?', on: :update


  # Validar  que la suma de los procesos en sus porcentajes no supera el 100
  # No se tiene el último en cuenta pues este es la suma de los porcentajes
  def max_percent_new
    id_last = Estado.active.select(:id).last_estado.id
    current_sum = Estado.where("id <> ?", id_last).sum(:facturar_al)
    sum = current_sum + facturar_al
    errors.add(:facturar_al, "La suma de los porcentajes es mayor a 100%") if sum > 100 and secuencia < id_last
  end

  def max_percent_update
    id_last = Estado.select(:id).last_estado.id
    current_sum = Estado.where("id <> ? AND id <> ?", id_last, id).sum(:facturar_al)
    sum = current_sum + facturar_al
    errors.add(:facturar_al, "La suma de los porcentajes es mayor a 100%") if sum > 100 and id != id_last
  end

  def facturar_al=(val)
    self[:facturar_al] = facturar ? val : 0
  end

  def manual
    self.pasa_manual ? "Sí" : "No"
  end
  # Get name para los formularios que usan desplegables
  def name
    self.estado.upcase
  end

  def pasa
    self.pasa_cantidad ? "Sí" : "No"
  end

  # Seguimiento anterior
  def prev
    Estado.active.where("secuencia < ?", self.secuencia).order("secuencia desc").limit(1).first
  end
  # Proceso siguiente
  def next
    Estado.active.where("secuencia > ?", self.secuencia).order("secuencia asc").limit(1).first
  end

  def factura_asi
    if self.facturar
      +self.facturar_al
    else
      "No factura"
    end
  end

  # Traer el último con base a la secuencia
  def self.last_estado
    Estado.active.order("secuencia desc").limit(1).first
  end

  def self.active
    where(active: true)
  end

  def self.inactive
    where(active: false)
  end

end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  before_action :set_estado, only: [:edit, :update, :destroy, :unlock, :lock]

  def index
    this = Estado
    @estados = this.where(active: true)
    @estados_inactive = this.where(active: false)
  end

  def edit
    puts action_name
    respond_to do |format|
      format.js { render "new_edit" }
    end
  end

  def new
    @estado = Estado.new
    respond_to do |format|
      format.js { render "new_edit" }
    end
  end

  def update
    respond_to do |format|
      if @estado.update(params_estado)
        puts @estado.facturar_al
        format.js { render "create_update" }
      else
        puts @estado.errors.full_messages
        @estado.reload
        format.js { render "create_update" }
      end
    end
  end

  def create
    @estado = Estado.new(params_estado)
    respond_to do |format|
      @save = @estado.save
      if @save
        @estado = Estado.last
        format.js { render "create_update" }
      else
        puts  @estado.errors.full_messages
        format.js { render "create_update" }
      end
    end
  end

  def destroy
    before = Before::Delete.new
    @removed = false
    if !before.child_records(@estado)
      @id = @estado.id
      @removed = true
      @estado.destroy
    end
    respond_to :js
  end

  def lock
    @estado.update_attribute(:active, false)
    respond_to :js
  end

  def unlock
    @estado.update_attribute(:active, true)
    respond_to :js
  end

  private

  def set_estado
    @estado = Estado.find(params[:id])
  end

  def params_estado
    params.require(:estado).permit(:estado, :nombre_accion, :pasa_cantidad, :color, :color_claro, :secuencia, :facturar, :facturar_al, :pasa_manual)
  end
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/views/estados/_actives.html.erb
<div class="row">
  <div id="box-estados" class="col-md-12">
    <div class="box box-primary">
      <div class="box-body table-responsive">
        <table class="table table-bordered table-striped" id="actives">
          <caption>
            <div class="pull-left">
              <strong>Proceso:</strong> Nombre que se mostrará mientras el lote está en ese proceso <br>
              <strong>Nombre como acción:</strong> Nombre que se muestra para la opción rápida para el siguiente estado
              <br>
              <strong>Color fuerte:</strong> Con este se resalta el lote en la programación y en el calendario <br>
              <strong>Color claro:</strong> Con este se resalta el resto de información del lote
            </div>
            <% if can? :create, User %>
                <div class="pull-right">
                  <%= link_to new_estado_path, remote: true do %>
                      <i class="fa fa-plus fa-2x"></i>
                  <% end %>
                </div>
            <% end %>
          </caption>
          <thead>
          <tr>
            <% destroy = can? :destroy, Estado %>
            <% update = can? :update, Estado %>
            <% if update || destroy %>
                <th colspan="<%= destroy && update ? "2" : "1" %>">Opc.</th>
            <% end %>
            <th>Proceso</th>
            <th>Nombre como acción</th>
            <th>Secuencia</th>
            <th>Pasar cantidad automáticamente</th>
            <th>Paso manual de unidades</th>
            <th>Factura (%)</th>
            <th>Color fuerte</th>
            <th>Color suave</th>
          </tr>
          </thead>
          <tbody>
          <% if @estados.empty? %>
              <%= render 'row', actions: true, empty: true %>
          <% else %>
              <% @estados.each do |estado| %>
                  <%= render 'row', estado: estado, actions: true, empty: false %>
              <% end %>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/estados/_edit.html.erb
<div class="col-md-6">
  <div class="box box-primary">
    <div class="box-header">
      <h3 class="box-title">Editar</h3>
    </div>
    <% puts "estado es : #{@estado}" %>
    <%= render "form", estado: @estado %>
  </div>
</div>

app/views/estados/_form.html.erb
<%= simple_form_for @estado, remote: true do |f| %>
    <div class="box-body">
      <div class="row">
        <div class="col-md-6">
          <%= f.input :estado %>
        </div>
        <div class="col-md-6">
          <%= f.input :secuencia, input_html: {min: 0} %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <%= f.input :nombre_accion %>
        </div>
        <div class="col-md-3">
          <%= f.input :pasa_cantidad, as: :select, collection: [["Sí", true], ["No", false]], required: true %>
        </div>
        <div class="col-md-3">
          <%= f.input :pasa_manual, as: :select, collection: [["Sí", true], ["No", false]], required: true %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <%= f.input :facturar, as: :select, collection: [["Sí", true], ["No", false]], required: true %>
        </div>
        <div class="col-md-6">
          <%= f.input :facturar_al, wrapper: :vertical_input_group do%>
              <div class="input-group">
                <div class="input-group-addon">
                  <i class="fa fa-percent"></i>
                </div>
                <%= f.input :facturar_al, label: false, input_html:{min: 0, max: 100, class: "form-control"}, readonly: !estado.facturar %>
              </div>
          <% end %>
        </div>
      </div>

      <hr>
      <!--Colores del estado-->
      <div class="row">
        <div class="col-md-6">
          <%= f.input :color, wrapper: :vertical_input_group do %>
              <div class="input-group my-colorpicker">
                <%= f.input_field :color, class: "form-control" %>
                <div class="input-group-addon">
                  <i></i>
                </div>
              </div>
          <% end %>
        </div>
        <div class="col-md-6">
          <%= f.input :color_claro, wrapper: :vertical_input_group do %>
              <div class="input-group my-colorpicker">
                <%= f.input_field :color_claro, class: "form-control" %>
                <div class="input-group-addon">
                  <i></i>
                </div>
              </div>
          <% end %>
        </div>
      </div>
      <table class="table table-bordered">
        <caption>
          Vista previa
        </caption>
        <thead>
        <tr>
          <th>Sec</th>
          <th>Estado</th>
          <th>Referencia</th>
        </tr>
        </thead>
        <tbody>
        <tr id="preview">
          <td class="text-center no-padding">
            <input type="number" value="1" class="form-control no-padding text-center" style="max-width: 3em;"></td>
          <td id="preview-td"><%= Estado.first.name %></td>
          <td>REFERENCIA</td>
        </tr>
        </tbody>
      </table>
    </div>
    <div class="box-footer">
      <div class="box-tools pull-right">
        <%= f.button :button, :class => "btn btn-primary btn-sm" do %>
            <i class="fa fa-floppy-o"></i>
            Guardar
        <% end %>
        <%= f.button :button, :type => "button", :class => "btn btn-default btn-sm" do %>
            <i class="fa fa-close"></i>
            Cancelar
        <% end %>
      </div>
    </div>
<% end %>
<script type="text/javascript" charset="utf-8">
    $(".my-colorpicker").colorpicker();
</script>

app/views/estados/_inactives.html.erb
<div class="row">
  <div id="box-estados" class="col-md-12">
    <div class="box box-primary">
      <div class="box-body table-responsive">
        <table class="table table-bordered table-striped" id="inactives">
          <caption>
            <h3>Procesos inactivos</h3>
            <small>Estos procesos no son tenidos en cuenta en el sistema</small>
          </caption>
          <thead>
          <tr>
            <th colspan="2"></th>
            <th>Proceso</th>
            <th>Nombre como acción</th>
            <th>Secuencia</th>
            <th>Pasar cantidad automáticamente</th>
            <th>Paso manual de unidades</th>
            <th>Factura (%)</th>
            <th>Color fuerte</th>
            <th>Color suave</th>
          </tr>
          </thead>
          <tbody>
          <% if @estados_inactive.empty? %>
              <%= render 'row', actions: false, empty: true%>
          <% else %>
              <% @estados_inactive.each do |estado| %>
                  <%= render 'row', estado: estado, actions: false, empty: false %>
              <% end %>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/estados/_new.html.erb
<div class="col-md-6">
  <div class="box box-primary">
    <div class="box-header">
      <h3 class="box-title">Nuevo proceso</h3>
    </div>
    <% puts "estado es : #{@estado}" %>
    <%= render "form", estado: @estado %>
  </div>
</div>

app/views/estados/_row.html.erb
<% if empty %>
    <tr data-empty="true">
      <td colspan="<%= can?(:udpate, Estado) ? "10": "8" %>" >No hay datos disponibles</td>
    </tr>
<% else %>
<tr data-id="<%= estado.id %>">
  <% if actions %>
      <% if can? :update, Estado %>
          <td>
            <%= link_to edit_estado_path(estado), remote: true, title: "Editar" do %>
                <i class="fa fa-pencil"></i>
            <% end %>
          </td>
      <% end %>
      <% if can? :destroy, Estado %>
          <td>
            <%= link_to lock_estado_path(estado), remote: true, method: :patch, class: "text-red", title: "Desactivar" do %>
                <i class="fa fa-lock"></i>
            <% end %>
          </td>
      <% end %>
  <% else %>
      <td>
        <%= link_to unlock_estado_path(estado), remote: true, method: :patch, class: "text-blue", title: "Activar" do %>
            <i class="fa fa-unlock "></i>
        <% end %>
      </td>
      <td>
        <%= link_to estado_path(estado), remote: true, method: :delete, class: " text-red", title: "Eliminar" do %>
            <i class="fa fa-trash"></i>
        <% end %>
      </td>
  <% end %>
  <td><%= estado.estado %></td>
  <td><%= estado.nombre_accion %></td>
  <td><%= estado.secuencia %></td>
  <td><%= estado.pasa %></td>
  <td><%= estado.manual %></td>
  <td><%= estado.factura_asi %></td>
  <td><%= estado.color %>
    <small class="pull-right"><i class="fa fa-square fa-lg" style="color: <%= estado.color %>;"></i></small>
  </td>
  <td><%= estado.color_claro %>
    <small class="pull-right"><i class="fa fa-square fa-lg" style="color: <%= estado.color_claro %>;"></i></small>
  </td>
</tr>
<% end %>

app/views/estados/create_update.js.erb
<% # En caso de que resulte con falla la acción también se ponen los errores correspondientes %>
<% if @estado.errors.any? %>
  error = "has-error";
  span = "<span class='help-block'></span>";

  <% @estado.errors.each do |attr, error| %>
    selector = "#estado_<%= attr %>";
    div = $(selector).parent();
    group = div.parent();
    if(group.hasClass("input-group")){
        parent_group = group.parent();
        parent_group.children("span.help-block").remove();
        parent_group.removeClass("has-error").addClass("has-error");
        parent_group.append(span);
        parent_group.children("span.help-block").append("<%= error %>");
    }else{
        div.children("span.help-block").remove();
        div.removeClass("has-error").addClass("has-error");
        div.append(span);
        div.children("span.help-block").append("<%= error %>");
    }
  <% end %>

<% else %>
  box_next = $("#box-estados").removeClass("col-md-6").addClass("col-md-12").next();
  row = "<%= j render 'row',  estado: @estado, actions: true, empty: false %>";
  <% if action_name == "update" %>
    box_next.remove();
    tr = $("table").find("[data-id='<%= @estado.id %>']");
    tr.replaceWith(row);
  <% else %>
    box_next.remove();
    $("table#actives tbody").append(row);
  <% end %>
<% end %>

app/views/estados/destroy.js.erb
<% puts @removed %>
<% if @removed %>
message = "Registro eliminado con éxito";
$("tr[data-id='<%= @id %>']").remove();
<% else %>
message = "No se puede eliminar este proceso porque hay registros de ciclos dependientes es este";
<% end %>
$.floatingMessage(message, {
    position: "bottom-right",
    height: 80,
    time: 4000,
    className: "ui-state-<%= @removed ? "active" : "error" %>"
});

app/views/estados/index.html.erb
<%= content_for :content_header do %>
    <h1>
      Procesos
      <small>Estados que los lotes atraviesan en el proceso de producción.</small>
    </h1>
<% end %>
<%= content_for :content_breadcrumb do %>
    <li><%= link_to "Procesos", estados_path %></li>
<% end %>
<%= content_for :title do %>
    Procesos
<% end %>

<%= render "actives" %>

<% if can? :unlock, User or can? :destroy, User %>
<%= render "inactives" %>
<% end %>

app/views/estados/lock.js.erb
$("tr[data-empty]").remove();
$("tr[data-id='<%= @estado.id %>']").remove();
tbody = $("table#inactives tbody");
tbody.append("<%= j render partial: "row", locals: { estado: @estado, actions: false, empty: false } %>");
if (tbody.length < 1) {
    tbody.append("<%= j render partial: "row", locals: { empty: true  } %>");
}
$.floatingMessage("Proceso desactivado", {
    position: "bottom-right",
    height: 80,
    time: 4000,
    className: "ui-state-active"
});

app/views/estados/new_edit.js.erb
<%
  file = action_name
  if action_name.eql?("update")
    file = "edit"
  elsif action_name.eql?("create")
    file = "new"
  end
%>
box = $("#box-estados");
box.removeClass("col-md-12 col-md-6").addClass("col-md-6");
box.next().remove();
box.after("<%= j render file, estado: @estado %>");

app/views/estados/unlock.js.erb
$("tr[data-empty]").remove();
$("tr[data-id='<%= @estado.id %>']").remove();
$("table#actives tbody").append("<%= j render 'row',  estado: @estado, actions: true, empty: false %>");
tbody = $("table#inactives tbody");
if (tbody.find("tr").length < 1) {
    tbody.append("<%= j render partial: "row", locals: { empty: true  } %>");
}
$.floatingMessage("Proceso activado", {
    position: "bottom-right",
    height: 80,
    time: 4000,
    className: "ui-state-active"
});